In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import string

In [5]:
a=np.array(list(string.ascii_uppercase))

In [6]:
a

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [7]:
df=pd.DataFrame({"A":[1,2,3],"B":[4,5,6]})

In [8]:
df

A  B
0  1  4
1  2  5
2  3  6

In [9]:
df1=pd.Series([7,8,9])

In [10]:
df['C']=df1

In [11]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [16]:
row={"A":4,"B":5,"C":6}

In [19]:
df=df.append(row,ignore_index=True)

In [20]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
3  4  5  6

In [21]:
df.drop([2])

A  B  C
0  1  4  7
1  2  5  8
3  4  5  6

In [26]:
df.drop("B",axis=1)

A  C
0  1  7
1  2  8
2  3  9
3  4  6

In [27]:
df.rename(columns={"C":"D"})

A  B  D
0  1  4  7
1  2  5  8
2  3  6  9
3  4  5  6

In [28]:
df=pd.read_csv("iris.csv")

In [29]:
df


sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [31]:
x=df.iloc[:,[0,1,2,3]]

In [32]:
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [33]:
y=df.iloc[:,4]

In [34]:
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
labelencoder_y=LabelEncoder()

In [37]:
y=labelencoder_y.fit_transform(y)

In [38]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2)

In [46]:
x_train.size

480

In [47]:
x_test.size

120

In [48]:
y_train.size

120

In [49]:
y_test.size

30

In [51]:
df["variety"].value_counts()

Virginica     50
Setosa        50
Versicolor    50
Name: variety, dtype: int64

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [56]:
classifier_knn.fit(x_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [120, 30]

In [57]:
x_train.shape

(120, 4)

In [58]:
y_train.shape

(30, 4)

In [59]:
y_train=y_train.reshape(-1,1)

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [62]:
x_train.size

480

In [63]:
y_train.size

120

In [64]:
x_test.size

120

In [65]:
y_test.size

30

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [68]:
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [69]:
y_pred=classifier_knn.predict(x_test)

In [70]:
y_pred

array([2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 1, 0, 1, 0, 2], dtype=int64)

In [71]:
y_pred.sort()

In [72]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [73]:
y_test

array([2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 1, 0, 1, 0, 2], dtype=int64)

In [74]:
y_test.sort()

In [75]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [76]:
from sklearn.metrics import confusion_matrix

In [77]:
confusion_matrix(y_pred,y_test)

array([[ 9,  0,  0],
       [ 0,  7,  1],
       [ 0,  0, 13]], dtype=int64)

In [78]:
confusion_matrix(y_test,y_pred)

array([[ 9,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 13]], dtype=int64)

In [85]:
classifier_knn.score(x_test,y_test)

0.4

In [80]:
from sklearn.metrics import accuracy_score

In [83]:
accuracy_score(y_pred,y_test)

0.9666666666666667

In [86]:
from sklearn.linear_model import LogisticRegression

In [87]:
logmodel=LogisticRegression()

In [88]:
logmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [90]:
y_pred=logmodel.predict(x_test)

In [91]:
y_pred

array([2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 1, 0, 1, 0, 2], dtype=int64)

In [92]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [94]:
from sklearn.metrics import confusion_matrix

In [96]:
confusion_matrix(y_test,y_pred)

array([[3, 2, 4],
       [3, 1, 3],
       [3, 4, 7]], dtype=int64)

In [97]:
logmodel.score(x_test,y_test)

0.36666666666666664

In [98]:
from sklearn.metrics import accuracy_score

In [99]:
accuracy_score(y_pred,y_test)

0.36666666666666664

In [100]:
from sklearn.naive_bayes import GaussianNB

In [101]:
classifier_nb=GaussianNB()

In [102]:
classifier_nb.fit(x_train,y_train)

GaussianNB(priors=None)

In [103]:
y_pred=classifier_nb.predict(x_test)

In [104]:
y_pred

array([2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 1, 0, 1, 0, 2], dtype=int64)

In [105]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [106]:
from sklearn.metrics import confusion_matrix

In [107]:
confusion_matrix(y_test,y_pred)

array([[3, 2, 4],
       [3, 2, 2],
       [3, 4, 7]], dtype=int64)

In [108]:
classifier_nb.score(x_test,y_test)

0.4

In [109]:
from sklearn.svm import SVC

In [110]:
classifier_svm_sig=SVC(kernel="sigmoid")

In [111]:
classifier_svm_sig.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [112]:
y_pred=classifier_svm_sig.predict(x_test)

In [113]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [114]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [115]:
from sklearn.metrics import confusion_matrix

In [116]:
confusion_matrix(y_test,y_pred)

array([[ 0,  9,  0],
       [ 0,  7,  0],
       [ 0, 14,  0]], dtype=int64)

In [117]:
classifier_svm_sig.score(x_test,y_test)

0.23333333333333334

In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [5]:
deef=pd.read_csv("iris.csv")

In [6]:
deef

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [7]:
x=deef.iloc[:,[0,1,2,3]]

In [15]:
y=deef.iloc[:,4]

In [16]:
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
labelencoder_y=LabelEncoder()

In [19]:
y=labelencoder_y.fit_transform(y)

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_split,y_train,y_split=train_test_split(x,y,test_size=0.3)

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
classifier_d=DecisionTreeClassifier()

In [28]:
classifier_d.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [30]:
y_pred=classifier_d.predict(x_split)

In [31]:
y_pred

array([2, 1, 1, 2, 2, 2, 0, 1, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 0, 2, 2, 2,
       0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1,
       2], dtype=int64)

In [32]:
y_split

array([2, 1, 1, 2, 2, 2, 0, 1, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 0, 2, 2, 2,
       0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1,
       2], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_split,y_pred)

array([[10,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 20]], dtype=int64)

In [38]:
classifier_d.score(x_split,y_split)

1.0

In [40]:
from sklearn.ensemble import RandomForestRegressor

C:\Users\mehak\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
