In [1]:
import numpy as np

In [2]:
#To create a array
arr=np.array([2,3,4,5])
print(arr)

[2 3 4 5]


In [8]:
#To access element
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[-1])  #to print last element


1
2
5


In [9]:
#Arithmetic operation
arr1=np.array([2,4,6,8])
arr2=np.array([4,8,12,16])
print(arr1 + arr2)

[ 6 12 18 24]


In [10]:
print(arr1 * arr2)

[  8  32  72 128]


In [11]:
print(arr1 / arr2)

[0.5 0.5 0.5 0.5]


In [13]:
#Matrix multiplication
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]


In [16]:
#generate random number between 0 to 9
a=np.random.randint(10)
a

3

In [1]:
import numpy as np

In [2]:
arr=np.array(["Ami","Mehak"])
arr

array(['Ami', 'Mehak'], dtype='<U5')

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr=np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr=np.random.randint([10])
arr

array([7])

In [7]:
zes=np.zeros([3])
zes

array([0., 0., 0.])

In [8]:
zes=np.zeros([3,3])
zes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
zes=np.ones([3])
zes

array([1., 1., 1.])

In [10]:
zes=np.ones([3,3])
zes

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#to create 1 on diagonals only
b=np.eye(2)
b

array([[1., 0.],
       [0., 1.]])

In [12]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
c=np.linspace(0,1,10)
c

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
lis=[1,11,12,90,89,45,67,78,18]
a=np.array(lis)
print(lis)

[1, 11, 12, 90, 89, 45, 67, 78, 18]


In [19]:
print("MINIMUM IS :" ,a.min())

MINIMUM IS : 1


In [20]:
print("Maximum is :",a.max())

Maximum is : 90


In [21]:
print("Argmin:",a.argmin())

Argmin: 0


In [22]:
print("Argmax:",a.argmax())

Argmax: 3


In [23]:
print("Sum:",a.sum())

Sum: 411


In [24]:
print("STD",a.std())

STD 34.058772731852805


In [25]:
print("Mean",a.mean())

Mean 45.666666666666664


In [26]:
import numpy as np

In [31]:
arr2=([[1,2],[3,4],[5,6],[7,8]])
b=np.array(arr2)
b
print("sum :",b.sum())


sum : 36


In [32]:
#To print horizontally or vertically
print("Sum:",b.sum(axis=0))

Sum: [16 20]


In [33]:
print("Sum:",b.sum(axis=1))

Sum: [ 3  7 11 15]


In [37]:
#Array shape in numpy
import numpy as np
bac=np.zeros((3,3))
bac
             


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
print(bac.shape)

(3, 3)


In [42]:
ran=np.random.randint(1,100,25)
ran

array([99, 52, 98, 55, 14, 92, 60, 44, 75, 52, 47, 86, 10, 83, 52, 61, 50,
        4, 68, 96, 58, 44, 85, 18, 37])

In [43]:
b=ran.reshape(5,5)
b

array([[99, 52, 98, 55, 14],
       [92, 60, 44, 75, 52],
       [47, 86, 10, 83, 52],
       [61, 50,  4, 68, 96],
       [58, 44, 85, 18, 37]])

In [50]:
ab=np.array([['a','b','c'],['d','e','f'],['g','h','i']])
print(ab)
print("single: ",ab[2,0])




[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
single:  g
single:  g


In [52]:
ab=np.array([['a','b','c'],['d','e','f'],['g','h','i']])
print(ab)


print("single: ",ab[2][0])

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
single:  g


In [57]:

#slicing
ab=np.array(['a','b','c','d','e','f','g','h','i'])
print(ab)


['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']


In [58]:
print(ab[2:5])

['c' 'd' 'e']


In [59]:
print(ab[:5])

['a' 'b' 'c' 'd' 'e']


In [60]:
print(ab[2:7:2])

['c' 'e' 'g']


In [61]:
print(ab[::-1])

['i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']


In [ ]:
  ####PANDAS
    
    