In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("iris.csv")
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
df['variety'].value_counts()

Versicolor    50
Setosa        50
Virginica     50
Name: variety, dtype: int64

In [7]:
x=df.iloc[:,0:4]
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [8]:
y=df.iloc[:,4]

In [9]:
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [13]:
#convert y in number encoding

from sklearn.preprocessing import LabelEncoder

In [14]:
labelencoder_y=LabelEncoder()

In [15]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

In [23]:
x_train.size

360

In [24]:
y_train

array([2, 2, 1, 1, 0, 2, 1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 2, 1, 2, 2, 1, 2,
       1, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 2, 1, 2, 0,
       2, 1, 1, 2, 1, 2, 0, 2, 0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 2, 0, 1, 0,
       2, 0, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 0, 1,
       2, 2], dtype=int64)

In [25]:
y_test

array([0, 1, 2, 0, 1, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 2, 0, 2, 2, 2, 1, 2, 0, 1, 0], dtype=int64)

In [26]:
x_test

sepal.length  sepal.width  petal.length  petal.width
21            5.1          3.7           1.5          0.4
95            5.7          3.0           4.2          1.2
130           7.4          2.8           6.1          1.9
47            4.6          3.2           1.4          0.2
51            6.4          3.2           4.5          1.5
70            5.9          3.2           4.8          1.8
24            4.8          3.4           1.9          0.2
88            5.6          3.0           4.1          1.3
91            6.1          3.0           4.6          1.4
5             5.4          3.9           1.7          0.4
112           6.8          3.0           5.5          2.1
143           6.8          3.2           5.9          2.3
46            5.1          3.8           1.6          0.2
42            4.4          3.2           1.3          0.2
49            5.0          3.3           1.4          0.2
106           4.9          2.5           4.5          1.7
39            5.1          3.4           1.5          0.2
119           6.0          2.2           5.0          1.5
13            4.3          3.0           1.1          0.1
45            4.8          3.0           1.4          0.3
110           6.5          3.2           5.1          2.0
29            4.7          3.2           1.6          0.2
134           6.1          2.6           5.6          1.4
149           5.9          3.0           5.1          1.8
22            4.6          3.6           1.0          0.2
117           7.7          3.8           6.7          2.2
68            6.2          2.2           4.5          1.5
69            5.6          2.5           3.9          1.1
0             5.1          3.5           1.4          0.2
35            5.0          3.2           1.2          0.2
107           7.3          2.9           6.3          1.8
19            5.1          3.8           1.5          0.3
80            5.5          2.4           3.8          1.1
124           6.7          3.3           5.7          2.1
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
77            6.7          3.0           5.0          1.7
55            5.7          2.8           4.5          1.3
44            5.1          3.8           1.9          0.4
108           6.7          2.5           5.8          1.8
63            6.1          2.9           4.7          1.4
76            6.8          2.8           4.8          1.4
6             4.6          3.4           1.4          0.3
58            6.6          2.9           4.6          1.3
25            5.0          3.0           1.6          0.2
52            6.9          3.1           4.9          1.5
4             5.0          3.6           1.4          0.2
48            5.3          3.7           1.5          0.2
8             4.4          2.9           1.4          0.2
84            5.4          3.0           4.5          1.5
100           6.3          3.3           6.0          2.5
27            5.2          3.5           1.5          0.2
123           6.3          2.7           4.9          1.8
125           7.2          3.2           6.0          1.8
127           6.1          3.0           4.9          1.8
66            5.6          3.0           4.5          1.5
132           6.4          2.8           5.6          2.2
7             5.0          3.4           1.5          0.2
59            5.2          2.7           3.9          1.4
18            5.7          3.8           1.7          0.3

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
logmodel=LogisticRegression()

In [55]:
logmodel.fit(x_train,y_train)
LogisticRegression()

ValueError: could not convert string to float: 'Good'

In [57]:
y_pred=logmodel_predict(x_test)
y_pred

NameError: name 'logmodel_predict' is not defined

In [58]:
from sklearn.linear_model import LogisticRegression

# define the logistic regression model
log_model = LogisticRegression()

# fit the model to the training data
log_model.fit(x_train, y_train)

# make predictions on the test data
y_pred = log_model.predict(x_test)

# print the predicted values
print(y_pred)


ValueError: could not convert string to float: 'Good'

In [59]:
import numpy as np

In [60]:
import pandas as pd


In [61]:
iri=pd.read_csv("iris.csv")

In [62]:
iri

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [63]:
x=iri.iloc[:,0:4]
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [65]:
y=iri.iloc[:,4]
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
labelencoder_y=LabelEncoder()

In [71]:
y=labelencoder_y.fit_transform(y)

In [72]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [74]:
from sklearn.model_selection import train_test_split

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [77]:
x_train.size

420

In [78]:
x_test.size

180

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [82]:
y_pred=logmodel.predict(x_test)

In [83]:
y_pred

array([2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 1, 0, 0, 1, 1, 2, 1, 0,
       0, 1, 0, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 2, 2, 0, 0,
       0], dtype=int64)

In [84]:
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

In [85]:
y_test

array([2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 0,
       0, 1, 0, 2, 1, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 2, 0, 1, 2, 2, 0, 0,
       0], dtype=int64)

In [86]:
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

In [87]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(y_test,y_pred)

array([[17,  0,  0],
       [ 0, 13,  0],
       [ 0,  2, 13]], dtype=int64)

In [90]:
logmodel.score(x_test,y_test)

0.9555555555555556

In [92]:
from sklearn.svm import SVC

In [94]:
classifier_svc_sig=SVC(kernel="sigmoid")

In [95]:
classifier_svc_sig

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [98]:
classifier_svc_sig.fit(x_train,x_train)

ValueError: bad input shape (105, 4)